# ======================================== Docker file mono stage  843MB ===========================================
#FROM mcr.microsoft.com/dotnet/sdk:5.0
#RUN mkdir /app
#WORKDIR /app
#COPY mvc1.csproj .
#RUN dotnet restore
#COPY . .
#RUN dotnet publish --configuration release --output dist
#ENV ASPNETCORE_URLS=http://+:80  
#EXPOSE 80
#CMD [ "dotnet","dist/mvc1.dll" ]
# ======================================== Docker file multi stage 215MB ========================================
# Estágio 1 - Base
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS Base
RUN mkdir /app
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:80  
EXPOSE 80

#Estágio 2 - Publish
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS publish
RUN mkdir /app
WORKDIR /app
COPY mvc1.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish --configuration release --output dist

#Estágio 3 - Final
FROM base AS final
WORKDIR /dist
COPY --from=publish /app/dist .
ENTRYPOINT ["dotnet","mvc1.dll"]

